use_frameworks!

platform :ios, '16.2'

install! 'cocoapods', :deterministic_uuids => false
install! 'cocoapods', :disable_input_output_paths => true

target 'BookingCalendar_Example' do
  pod 'BookingCalendar', :path => '../'

  target 'BookingCalendar_Tests' do
    inherit! :search_paths

  end
end
